### ISSUE TITLE
Too Hard

### ISSUE THREAD

**Issue by tnfssc** [pegasusVikas/MyGame#1]
The game is extremely hard. My highest score is 0. :(

https://www.youtube.com/watch?v=u0ZjzzvIuHk

**Comment by MoaufmKlo** [comment]
Did you know that you can double jump?

**Comment by tnfssc** [comment]
> Did you know that you can double jump?

yeah i do, but my highest score is still zero

**Comment by pegasusVikas** [comment]
just check the console and tell me if there is any error

**Comment by tnfssc** [comment]
> just check the console and tell me if there is any error

No errors in console except favicon.ico. Your on screen score isn't updating in real-time.

**Comment by pegasusVikas** [comment]
which browser are you using?

**Comment by tnfssc** [comment]
> which browser are you using?

I am using Chrome v79. BTW try now.sh for static/serverless hosting
